apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  # sessionAffinity: ClientIP // check README.md
  selector:
    app: kubia
  ports:
    - port: 80
      targetPort: 8080 # or use named port from Pod spec