apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  # nodeSelector:
  #   gpu: "true" #for selecting node by label in node
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP